spring:
  application:
    name: service-feign
server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
feign:
  hystrix:
    enabled: true  #打开 feign 断路器