spring:
  application:
    name: eureka-server
server:
  port: 7002
eureka:
  instance:
    hostname: server3
  client:
    register-with-eureka: true # 表示是否将自己注册到 Eureka Server，默认为 true。
    fetch-registry: true #表示是否从 Eureka Server 获取注册信息，默认为 true
    service-url:
      #设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址。默认是 http://localhost:8761/eureka ；多个地址可使用英文逗号（,）分隔。
      defaultZone: http://server1:7000/eureka/,http://server2:7001/eureka/
